# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build release packs

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install deps
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Pack built files
      run: zip -r t2c.zip build/*
      
    - name: Create release
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: T2C - ${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        generate_release_notes: true
        files: |
          t2c.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload built file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: t2c.zip

